IF OBJECT_ID('CompaniesCategories','U') IS NOT NULL DROP TABLE CompaniesCategories;
IF OBJECT_ID('CompaniesSubcategories','U') IS NOT NULL DROP TABLE CompaniesSubcategories;
IF OBJECT_ID('Logos','U') IS NOT NULL DROP TABLE Logos;
IF OBJECT_ID('DayWeekTimeTables','U') IS NOT NULL DROP TABLE DayWeekTimeTables;
GO
IF OBJECT_ID('Photos','U') IS NOT NULL DROP TABLE Photos;
IF OBJECT_ID('Emails','U') IS NOT NULL DROP TABLE Emails;
IF OBJECT_ID('Phones','U') IS NOT NULL DROP TABLE Phones;
IF OBJECT_ID('SocialNets','U') IS NOT NULL DROP TABLE SocialNets;
IF OBJECT_ID('UsersCompanies','U') IS NOT NULL DROP TABLE UsersCompanies;
GO
IF OBJECT_ID('Companies','U') IS NOT NULL DROP TABLE Companies;
GO
IF OBJECT_ID('Addresses','U') IS NOT NULL DROP TABLE Addresses;
GO
IF OBJECT_ID('ZipCodes','U') IS NOT NULL DROP TABLE ZipCodes;
GO
IF OBJECT_ID('SocialNetNames','U') IS NOT NULL DROP TABLE SocialNetNames;
IF OBJECT_ID('Streets','U') IS NOT NULL DROP TABLE Streets;
IF OBJECT_ID('Cities','U') IS NOT NULL DROP TABLE Cities;
IF OBJECT_ID('Categories','U') IS NOT NULL DROP TABLE Categories;
IF OBJECT_ID('Subcategories','U') IS NOT NULL DROP TABLE Subcategories;
GO
CREATE TABLE Categories(
	CategoryId INT IDENTITY PRIMARY KEY
	,CategoryName NVARCHAR(256) NOT NULL
);
CREATE TABLE Subcategories(
	SubcategoryId INT IDENTITY PRIMARY KEY
	,SubcategoryName NVARCHAR(256) NOT NULL
);
CREATE TABLE Cities(
	CityId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY 
	,CityName NVARCHAR(150) NOT NULL
);
CREATE TABLE Streets(
	StreetId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY 
	,StreetName NVARCHAR(150) NOT NULL
	,CityId UNIQUEIDENTIFIER NULL 
		FOREIGN KEY REFERENCES Cities(CityId)
		ON DELETE NO ACTION
);
CREATE TABLE SocialNetNames(
	SocialNetNameId INT IDENTITY PRIMARY KEY
	,SocialNetName NVARCHAR(256)
);
GO
CREATE TABLE ZipCodes(
	ZipCodeId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY 
	,CityId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Cities(CityId)
		ON DELETE NO ACTION
	,ZipCode NVARCHAR(15) NOT NULL
);
GO
CREATE TABLE Addresses(
	AddressId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
	,ZipCodeId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES ZipCodes(ZipCodeId)
		ON DELETE NO ACTION
	,CityId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Cities(CityId)
		ON DELETE SET NULL
	,StreetId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Streets(StreetId)
		ON DELETE SET NULL
	,House NVARCHAR(12) NOT NULL
	,[Block] NVARCHAR(12) NULL
	,Apartment NVARCHAR(12) NULL
	,Latitude DECIMAL(22,18) NULL
	,Longitude DECIMAL(22,18) NULL
);
GO
CREATE TABLE Companies(
	CompanyId UNIQUEIDENTIFIER PRIMARY KEY
	,CreatedOn DATETIME
	,CompanyName NVARCHAR(256) NOT NULL
	,ParentCompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE NO ACTION
	,Director NVARCHAR(256) NOT NULL
	,DescriptionShort NVARCHAR(200) NULL
	,DescriptionFull NVARCHAR(2000) NULL
	,WebSite NVARCHAR(256) NULL
	,AddressId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Addresses(AddressId)
		ON DELETE SET NULL
	,Popularity INT NOT NULL DEFAULT(0)
);
GO
CREATE TABLE CompaniesCategories(
	CompanyCategoryId UNIQUEIDENTIFIER PRIMARY KEY
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,CategoryId INT NULL
		FOREIGN KEY REFERENCES Categories(CategoryId)
		ON DELETE SET NULL
);
CREATE TABLE CompaniesSubcategories(
	CompanySubcategoryId UNIQUEIDENTIFIER PRIMARY KEY
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,SubcategoryId INT NULL
		FOREIGN KEY REFERENCES Subcategories(SubcategoryId)
		ON DELETE SET NULL
);
CREATE TABLE DayWeekTimeTables(
	DayWeekTimeTableId UNIQUEIDENTIFIER PRIMARY KEY
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,[WeekDay] NVARCHAR(16) NOT NULL
	,[DayStart] NVARCHAR(8) NOT NULL
	,[DayEnd] NVARCHAR(8) NOT NULL
	,[LunchBreakStart] NVARCHAR(8) NULL
	,[LunchBreakEnd] NVARCHAR(8) NULL
);
GO
CREATE TABLE Photos(
	PhotoId UNIQUEIDENTIFIER PRIMARY KEY
	,CreatedOn DATETIME
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,[FileName] NVARCHAR(100) NOT NULL
);
CREATE TABLE Logos(
	PhotoId UNIQUEIDENTIFIER PRIMARY KEY
		FOREIGN KEY REFERENCES Photos(PhotoId)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
CREATE TABLE Emails(
	EmailId UNIQUEIDENTIFIER PRIMARY KEY
	,CreatedOn DATETIME
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,Email NVARCHAR(256) NOT NULL
);
CREATE TABLE Phones(
	PhoneId UNIQUEIDENTIFIER PRIMARY KEY
	,CreatedOn DATETIME
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,PhoneNumber NVARCHAR(13) NOT NULL
);
CREATE TABLE SocialNets(
	SocialNetId UNIQUEIDENTIFIER PRIMARY KEY
	,CreatedOn DATETIME
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
	,SocialNetURL NVARCHAR(500)
	,SocialNetNameId INT NULL
		FOREIGN KEY REFERENCES SocialNetNames(SocialNetNameId)
		ON DELETE SET NULL
);
CREATE TABLE UsersCompanies(
	UserCompanyId UNIQUEIDENTIFIER PRIMARY KEY
	,UserId UNIQUEIDENTIFIER NULL
	,CompanyId UNIQUEIDENTIFIER NULL
		FOREIGN KEY REFERENCES Companies(CompanyId)
		ON DELETE SET NULL
);
GO
